db:
  image: postgres

web_production:
  build: .
  dockerfile: Dockerfile.production
  command: bundle exec unicorn_rails -c config/unicorn.rb -E production -D
  volumes:
    - /tmp:/tmp
  links:
    - db
    - nginx

nginx:
  build: .
  dockerfile: Dockerfile.nginx
  volumes:
    - /tmp:/tmp
  ports:
    - 80:80
